
import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import { LoginBtn, LogoutBtn } from './loginBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let session = await getServerSession(authOptions);
  const USER_NAME = session?.user?.name;
  const USER_IMAGE = session?.user?.image;

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-gray-200 h-[60px] '>
          <div className='flex justify-between items-center h-full w-[50%] mx-auto'>
            <div className='flex'>
              <Link href="/">
                <div className='font-bold'>NEXT.JS</div>
              </Link>
              <Link href="/listboard">
                <div className='ml-[20px]'>메모장</div>
              </Link>
              <Link href="/articles">
                <div className='ml-[20px]'>리스트</div>
              </Link>
              <Link href="/fcmalert">
                <div className='ml-[20px]'>FCM알람</div>
              </Link>
            </div>
            {!USER_NAME ? (
              <div className='flex'>
                <div className='mr-4'>
                  <LoginBtn />
                </div>
                <Link href="/register">
                  <div>회원가입</div>
                </Link>
              </div>
            ) : (
              <div className='flex'>
                {USER_IMAGE && (
                  <div className='w-[30px] h-[30px] mr-4 inline-block align-middle'>
                    <img src={USER_IMAGE} className='rounded-full ' />
                  </div>
                )}
                <div>{USER_NAME}님</div>
                <div className='ml-4'>
                  <LogoutBtn />
                </div>
              </div>
            )}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
